// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gw_s3_handler

import (
	"github.com/99designs/gqlgen/graphql"
)

type S3File struct {
	Location string `json:"location"`
}

type UploadFile struct {
	File graphql.Upload `json:"file"`
}
